### ISSUE TITLE
How to handle multiple feature module navigation actions

### ISSUE THREAD

**Issue by Ezike** [Zhuinden/Jetpack-Navigation-Hilt-MultiModule-Example#2]
Hi Zhuinden, I have a question about how this pattern would scale in a big codebase - will the  single module Navigator implement all the actions from the different feature modules in the project or would you write a different navigator implementation for each feature module

**Comment by Zhuinden** [comment]
Hey, technically it would work either way, as the only thing that *actually matters* is that 1 implementation of the interface defined by the feature module is installed in Hilt's graph, otherwise the code would not compile - effectively making the approach more type-safe than the current approaches that people generally do (either deep-linking which equals to effectively doing string-ly typed navigation, or of reflection which is runtime exceptions in case of failure)

**Comment by Ezike** [comment]
Yea you are correct. Which approach would you prefer in terms of scale, maintainability and readability

**Comment by Zhuinden** [comment]
My mind's eye says that if modularization is heavily "by screen", then it is possible to define a parent gradle module for a set of screens, and then include that as "a feature module" for the :app, and then it truly is just features that move from A to B in :app navigator.

I think even if the root navigator is split into multiple files, it can make sense to have them in the same package. It feels like the same responsibility, overall. 🤔

**Comment by Ezike** [comment]
Thanks for the insight. I was able to implement something similar [here](https://github.com/Ezike/StarWarsSearch-MVI/blob/main/navigation/src/main/java/com/ezike/tobenna/starwarssearch/navigation/SearchScreenNavigator.kt)
